### ISSUE TITLE
파라미터 존재시 분기 필요

### ISSUE THREAD

**Issue by Jinjeok** [Jinjeok/boty#5]
파라미터가 존재 할때 이게 파라미터다 라고 하는걸 알 수 있게 해야함.
필요한 부분:
1. options.type
2. message formatting
3. 결과 출력

**Comment by murikubo** [comment]
허~허으어~아아~아아아~

**Comment by Jinjeok** [comment]
좋은 아이디어였지만 내가 이미 했단다 과거의 나야
